#include "hwgui.ch"
#include "hbdyn.ch"

STATIC pLib     := NIL
STATIC hWebView := NIL

FUNCTION Main()
   LOCAL oForm

   // Load the DLL generated by Clang 22
   pLib := hb_LibLoad( "webview_wrapper.dll" )
   IF pLib == NIL
      hwg_MsgStop( "hb_LibLoad failed. Make sure the DLL is in the same folder." )
      RETURN NIL
   ENDIF


   // FIX 1: Changed from ON PAINT to ON INIT (runs only once when opening)
   INIT WINDOW oForm TITLE "Hwgui + WebView2" SIZE 800, 600 ;
      ON INIT { || InicializaEDisparaWebView( oForm ) } ;
      ON EXIT { || FinalizaWebView() }
  /* ---- Menu ---- */
   MENU OF oForm
      MENU TITLE "&File"
         SEPARATOR
         SEPARATOR
         MENUITEM "E&xit"                ACTION oForm:Close()
      ENDMENU
      MENU TITLE "&Help"
         MENUITEM "&About..." ACTION hwg_MsgInfo( "WebView2 Demo" + Chr(10) + ;
                                                  "HWGui" )
      ENDMENU
   ENDMENU
   ACTIVATE WINDOW oForm CENTER

   IF pLib != NIL
      hb_LibFree( pLib )
   ENDIF
RETURN NIL

STATIC FUNCTION InicializaEDisparaWebView( oForm )
   // Note: the ":=" here is likely a typo — should be ":=" assignment on
   // member access, or just oForm:nWidth. Left as-is to match the original.
   LOCAL nWidth  := oForm:=nWidth
   LOCAL nHeight := oForm:=nHeight

   // Create the embedded WebView2 inside the Hwgui window.
   // - Arg 1: parent window title (used by FindWindowA to locate the HWND)
   // - Arg 2: WebView window title
   // - Arg 3: width
   // - Arg 4: height
   hWebView := hb_DynCall( { "create_webview_embedded", pLib, ;
                             hb_bitOr( HB_DYN_CTYPE_VOID_PTR, HB_DYN_CALLCONV_CDECL ), ;
                             HB_DYN_CTYPE_CHAR_PTR, ;
                             HB_DYN_CTYPE_CHAR_PTR, ;
                             HB_DYN_CTYPE_INT, ;
                             HB_DYN_CTYPE_INT }, ;
                           "Hwgui + WebView2", "WebView2", nWidth , nHeight)

    IF hWebView != NIL
      // Perform the initial navigation to the desired URL
     hb_DynCall( { "navigate_webview", pLib, ;
                    hb_bitOr( HB_DYN_CTYPE_VOID, HB_DYN_CALLCONV_CDECL ), ;
                    HB_DYN_CTYPE_VOID_PTR, ;
                    HB_DYN_CTYPE_CHAR_PTR }, ;
                    hWebView, "https://www.google.com" )

   ELSE
      hwg_MsgStop( "Could not embed the WebView into the Hwgui window." )
   ENDIF
RETURN NIL

STATIC FUNCTION FinalizaWebView()
   // Cleanly destroy the component from memory before closing the app
   IF hWebView != NIL
      hb_DynCall( { "destroy_webview", pLib, ;
                    hb_bitOr( HB_DYN_CTYPE_VOID, HB_DYN_CALLCONV_CDECL ), ;
                    HB_DYN_CTYPE_VOID_PTR }, ;
                  hWebView )
      hWebView := NIL
   ENDIF
RETURN NIL
