
name: checkubuntu

on:
  push:
  #schedule:
  # - cron: "15 5 1 * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'hwgui test'
        default: 'checkonly'
        required: true

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:

    - name: Build
      env:
         HB_BUILD_STRIP: all
         HB_COMPILER: gcc
      run: |
         sudo apt-get update
         sudo apt-get upgrade
         sudo apt-get install gcc
         sudo apt-get install make
         sudo apt-get install build-essential libgtk2.0-dev --fix-missing
         sudo apt-get install git
         git clone https://github.com/harbour/core /tmp/harbour --depth 1
         git clone https://github.com/JoseQuintas/hwgui_fork /tmp/hwgui --depth 1
         cd /tmp/harbour
         sudo make install
         cd /tmp/hwgui
         hbmk2 hwgui.hbp -workdir=/tmp -w3 -es2
         hbmk2 hbxml.hbp -workdir=/tmp -w3 -es2
         hbmk2 procmisc.hbp -workdir=/tmp -w3 -es2
         hbmk2 hwgdebug.hbp -workdir=/tmp -w3 -es2
         cd /tmp/hwgui/samples
         hbmk2 allhbp.hbp -workdir=/tmp -w3 -es2
